### ISSUE TITLE
As a Developer, I have to configure the Initial setup required and update the readme file to mention required softwares to be installed.

### ISSUE THREAD

**Issue by 161FA04368** [WSUCEG-7140/mystore-teamDelta#16]
Update readme file to mention the softwares and required versions to be required to run the application.

Push the design document to the code base.

Definition of Done:

Readme file will be updated and can be seen in repo.
1.1. Details of specific languages, frameworks and libraries
1.2 Preliminary database design such that its implementable in Database such as MySQL

**Comment by niharika-poreddy** [comment]
1. Basically follow the steps required to initial setup the software's required to create the project in our system.
4. As the frameworks selected are ReactJS for UI and Springboot for Backend..These are the steps that needs to follow to setup                                                                                                                                 
ReactJS setup:
Prerequisites are windows, VS Code and Nodejs
> Open Command Prompt
> Create a new project folder: 
     mkdir SHOPPINGCART 
> Move to that directory:
    cd SHOPPINGCART
> Install React using create-react-app, a tool that installs all of the dependencies to 
   build and run a full React.js application:
   npx create-react-app shoppingcart-app
>   cd shoppingcart-app
>   start your react app using
>   npm start

Springboot setup:

> Setup Java Development Kit (JDK) and set path
> Install Spring Boot CLI
 
Mysql setup:
>  Download the mysql community server edition software.
>  Once downlaoded, click the download file to install setup
